language: python
install:
  - pip install tox
script: tox
matrix:
    include:
        - python: 3.8
          env: TOXENV=py38-ci-cov-codecov,checkstyle,security
          dist: bionic
          sudo: false
          os: linux
