language: python
install:
  - pip install tox
script: tox
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27-ci-cov-codecov,checkstyle,security
          dist: trusty
          sudo: false
          os: linux
        - python: 3.5
          env: TOXENV=py35-ci
          dist: trusty
          sudo: false
          os: linux
