version: 1.0.{build}
environment:
  PYTHON: C:\\Python27
install:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python -m pip install --upgrade pip

    python -m pip install --upgrade virtualenv

    python -m pip install --upgrade tox

    mkdir C:\\tmp\\Trash
build: off
test_script:
- cmd: tox -e py-ci-cov
