version: 1.0.{build}
environment:
  PYTHON: C:\\Python37
  PYTHON64: C:\\Python37-x64
install:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python -m pip install --upgrade pip

    python -m pip install --upgrade virtualenv

    python -m pip install --upgrade tox

    SET PATH=%PYTHON64%;%PYTHON64%\\Scripts;%PATH%

    python -m pip install --upgrade pip

    python -m pip install --upgrade virtualenv

    python -m pip install --upgrade tox

    mkdir C:\\tmp\\Trash

build: off
test_script:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    tox -e py-ci-cov-codecov

    if %errorlevel% neq 0 exit /b %errorlevel%

    SET PATH=%PYTHON64%;%PYTHON64%\\Scripts;%PATH%

    tox -e py-ci
