#!/usr/bin/env python
from e3.os.process import Run
from e3.env import Env
import sys
import os


if __name__ == '__main__':
    os_name = Env().build.os.name
    script_dir = os.path.abspath(os.path.dirname(__file__))
    cmd = ['py.test' + Env().build.os.exeext]

    args = sys.argv[1:]

    if '--cov' in args:
        coverage_conf = '%s/coverage_%s.rc' % (script_dir, os_name)
        cmd.append('--cov-config=%s' % coverage_conf)
    if '--cov' in args and '--coveralls' in args:
        args = [arg for arg in args if arg != '--coveralls']
        run_coveralls = True
    else:
        run_coveralls = False

    p = Run(cmd + args,
            output=None,
            error=None)

    if run_coveralls:
        Run(['coveralls', '--rcfile=%s' % coverage_conf],
            output=None, error=None)

    sys.exit(p.status)
