#!/usr/bin/env python
from e3.os.process import Run
from e3.env import Env
import sys
import os


if __name__ == '__main__':
    os_name = Env().build.os.name
    script_dir = os.path.abspath(os.path.dirname(__file__))
    cmd = ['py.test' + Env().build.os.exeext]

    if '--cov' in sys.argv[1:]:
        cmd.append(
            '--cov-config=%s/coverage_%s.rc' % (script_dir, os_name))

    p = Run(cmd + sys.argv[1:],
            output=None,
            error=None)
    sys.exit(p.status)
